-- 1)Create database alumno
-- CREATE TABLE ALUMNO(ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME VARCHAR(20) NOT NULL,
-- LAST_NAME VARCHAR(20) NOT NULL);

-- 2) Insert a few rows
-- INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("JULIAN", "GARCIA");
-- INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("JULIAN", "SORIANO");
-- INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("JORGE", "GARCIA");

-- 3) Select all
-- SELECT * from ALUMNO;
-- 4) Select filtered
-- SELECT * from ALUMNO 
--  WHERE last_name="GARCIA";

-- DROP TABLE ALUMNO;