-- 1)Create database alumno
-- CREATE TABLE ALUMNO(ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME VARCHAR(20) NOT NULL,
-- LAST_NAME VARCHAR(20) NOT NULL);

-- 2) Drop table
-- DROP TABLE ALUMNO;
-- DELETE FROM ALUMNO WHERE ID==2;
-- 3) Insert into
-- INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("BENITO", "GARCIA");
-- INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("BENITO", "SUAREZ");
-- INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("JORGE", "GARCIA");
-- INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("LUIS", "DOMINGUEZ");
-- INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("MANUEL", "BUENROSTRO");
-- INSERT INTO ALUMNO(NAME,LAST_NA E) VALUES("ALEJANDRO", "MEJIA");
INSERT INTO ALUMNO(NAME,LAST_NAME) VALUES("ALEJANDRO", "SUAREZ");

-- 4) Select *(all)
SELECT * from ALUMNO;

-- 5) Select * where
SELECT * FROM ALUMNO WHERE NAME="BENITO";

-- 6) Select * where ... like 
SELECT * FROM ALUMNO WHERE LAST_NAME LIKE "%a";

-- 7) Select * where ... between
SELECT * FROM ALUMNO WHERE LAST_NAME BETWEEN "GARCIA" AND "ZAPATA";

-- 8) Select distinct
SELECT DISTINCT NAME FROM ALUMNO;
SELECT DISTINCT LAST_NAME, NAME FROM ALUMNO
ORDER BY NAME, LAST_NAME;

-- 9) Select where _ group by _ order by
SELECT * FROM ALUMNO GROUP BY NAME;